"""Loading Zone Data"""
class MapData:
    def __init__(self, name, map_id=0, map_dest=0, exit_dest=0, **kwargs):
        self.name = name
        self.map_id = map_id
        self.map_dest = map_dest
        self.exit_dest = exit_dest
        self.kongs()
        for key, value in kwargs.items():
            if hasattr(self, key):
                setattr(self, key, value)
            else:
                raise Exception("Attribute does not exist")

    def __str__(self):
        """Get the string.

        Returns:
            str: returns a string of the GB location.
        """
        return self.name

    def __repr__(self):
        """Get the string.

        Returns:
            str: returns a string of the GB location.
        """
        return self.name
    
    def kongs(self, dk=True, diddy=True, lanky=True, tiny=True, chunky=True):
        self.uses_dk = dk
        self.uses_diddy = diddy
        self.uses_lanky = lanky
        self.uses_tiny = tiny
        self.uses_chunky = chunky

# Type 1 = Standard, 2 = Snides Only/Unused
# Difficulty 2 is a difficult bonus barrel, otherwise 1 is default

loading_zones = [
    MapData( "DK Isles Overworld [DK Isles: Training Grounds]", map_id=34, map_dest=176, exit_dest=0, ),
    MapData( "DK Isles Overworld [DK Isles: Fairy Island]", map_id=34, map_dest=189, exit_dest=0, uses_dk=False, uses_diddy=False, uses_lanky=False, uses_chunky=False, ),
    MapData( "DK Isles Overworld [DK Isles: Snide's Room]", map_id=34, map_dest=195, exit_dest=0, ),
    MapData( "DK Isles Overworld [Jungle Japes Lobby]", map_id=34, map_dest=169, exit_dest=0, ),
    MapData( "DK Isles Overworld [Angry Aztec Lobby]", map_id=34, map_dest=173, exit_dest=0, ),
    MapData( "DK Isles Overworld [Frantic Factory Lobby]", map_id=34, map_dest=175, exit_dest=0, ),
    MapData( "DK Isles Overworld [Gloomy Galleon Lobby]", map_id=34, map_dest=174, exit_dest=0, ),
    MapData( "DK Isles Overworld [Fungi Forest Lobby]", map_id=34, map_dest=178, exit_dest=0, ),
    MapData( "DK Isles Overworld [Crystal Caves Lobby]", map_id=34, map_dest=194, exit_dest=0, ),
    MapData( "DK Isles Overworld [Creepy Castle Lobby]", map_id=34, map_dest=193, exit_dest=999, ),
    MapData( "DK Isles Overworld [Hideout Helm Lobby]", map_id=34, map_dest=170, exit_dest=0, ),
    MapData( "DK Isles: Training Grounds [DK Isles Overworld]", map_id=176, map_dest=34, exit_dest=0, ),
    MapData( "DK Isles: Training Grounds [DK Isles: DK's House]", map_id=176, map_dest=171, exit_dest=1, ),
    MapData( "DK Isles: DK's House [Training Grounds]", map_id=171, map_dest=176, exit_dest=1, ),
    MapData( "DK Isles: Fairy Island [DK Isles Overworld]", map_id=189, map_dest=34, exit_dest=8, ),
    MapData( "DK Isles: Snide's Room [DK Isles Overworld]", map_id=195, map_dest=34, exit_dest=9, ),
   
    MapData( "Jungle Japes Lobby [DK Isles Overworld]", map_id=169, map_dest=34, exit_dest=2, ),
    MapData( "Jungle Japes Lobby [Jungle Japes]", map_id=169, map_dest=7, exit_dest=999, ),
    MapData( "Jungle Japes [Jungle Japes Lobby]", map_id=7, map_dest=169, exit_dest=999, ),
    MapData( "Jungle Japes [Jungle Japes: Mountain]", map_id=7, map_dest=4, exit_dest=0, uses_dk=False, uses_lanky=False, uses_tiny=False, uses_chunky=False, ),
    MapData( "Jungle Japes [Jungle Japes: Lanky's Cave]", map_id=7, map_dest=13, exit_dest=0, uses_dk=False, uses_diddy=False, uses_tiny=False, uses_chunky=False, ),
    MapData( "Jungle Japes [Jungle Japes: Shell]", map_id=7, map_dest=12, exit_dest=0, uses_dk=False, uses_diddy=False, uses_lanky=False, uses_chunky=False, ),
    MapData( "Jungle Japes [Jungle Japes: Chunky's Cave]", map_id=7, map_dest=33, exit_dest=0, ),
    MapData( "Jungle Japes: Mountain [Jungle Japes]", map_id=4, map_dest=7, exit_dest=2, ), # Needs Testing
    MapData( "Jungle Japes: Mountain [Jungle Japes: Minecart]", map_id=4, map_dest=6, exit_dest=0, ), # Needs Testing
    MapData( "Jungle Japes: Minecart [Jungle Japes]", map_id=6, map_dest=7, exit_dest=14, ),
    MapData( "Jungle Japes: Lanky's Cave [Jungle Japes]", map_id=13, map_dest=7, exit_dest=5, ),
    MapData( "Jungle Japes: Shell [Jungle Japes]", map_id=12, map_dest=7, exit_dest=1, uses_dk=False, uses_lanky=False, uses_chunky=False, ), # Needs Testing
    MapData( "Jungle Japes: Chunky's Cave [Jungle Japes]", map_id=33, map_dest=7, exit_dest=8, ),

    MapData( "Angry Aztec Lobby [DK Isles Overworld]", map_id=173, map_dest=34, exit_dest=3, ),
    MapData( "Angry Aztec Lobby [Angry Aztec]", map_id=173, map_dest=38, exit_dest=999, ),
    MapData( "Angry Aztec [Angry Aztec Lobby]", map_id=38, map_dest=173, exit_dest=999, ),
    MapData( "Angry Aztec [Angry Aztec: 5 Door Temple (DK)]", map_id=38, map_dest=19, exit_dest=0, uses_diddy=False, uses_lanky=False, uses_tiny=False, uses_chunky=False, ),
    MapData( "Angry Aztec [Angry Aztec: 5 Door Temple (Diddy)]", map_id=38, map_dest=21, exit_dest=0, uses_dk=False, uses_lanky=False, uses_tiny=False, uses_chunky=False, ),
    MapData( "Angry Aztec [Angry Aztec: 5 Door Temple (Lanky)]", map_id=38, map_dest=23, exit_dest=0, uses_dk=False, uses_diddy=False, uses_tiny=False, uses_chunky=False, ),
    MapData( "Angry Aztec [Angry Aztec: 5 Door Temple (Tiny)]", map_id=38, map_dest=22, exit_dest=0, uses_dk=False, uses_diddy=False, uses_lanky=False, uses_chunky=False, ),
    MapData( "Angry Aztec [Angry Aztec: 5 Door Temple (Chunky)]", map_id=38, map_dest=24, exit_dest=0, uses_dk=False, uses_diddy=False, uses_lanky=False, uses_tiny=False, ),
    MapData( "Angry Aztec [Angry Aztec: Beetle Race]", map_id=38, map_dest=14, exit_dest=999, uses_dk=False, uses_diddy=False, uses_lanky=False, uses_chunky=False, ),
    MapData( "Angry Aztec: Tiny's Temple [Angry Aztec]", map_id=16, map_dest=38, exit_dest=1, ),
    MapData( "Angry Aztec: Llama Temple [Angry Aztec]", map_id=20, map_dest=38, exit_dest=2, ),
    MapData( "Angry Aztec: 5 Door Temple (DK) [Angry Aztec]", map_id=19, map_dest=38, exit_dest=5, ),
    MapData( "Angry Aztec: 5 Door Temple (Diddy) [Angry Aztec]", map_id=21, map_dest=38, exit_dest=6, ),
    MapData( "Angry Aztec: 5 Door Temple (Lanky) [Angry Aztec]", map_id=23, map_dest=38, exit_dest=7, ),
    MapData( "Angry Aztec: 5 Door Temple (Tiny) [Angry Aztec]", map_id=22, map_dest=38, exit_dest=3, ),
    MapData( "Angry Aztec: 5 Door Temple (Chunky) [Angry Aztec]", map_id=24, map_dest=38, exit_dest=4, ),
    MapData( "Angry Aztec: Beetle Race [Angry Aztec]", map_id=14, map_dest=38, exit_dest=999, ),

    MapData( "Frantic Factory Lobby [DK Isles Overworld]", map_id=175, map_dest=34, exit_dest=4, ),
    MapData( "Frantic Factory Lobby [Frantic Factory]", map_id=175, map_dest=26, exit_dest=999, ),
    MapData( "Frantic Factory [Frantic Factory Lobby]", map_id=26, map_dest=175, exit_dest=999, ),
    MapData( "Frantic Factory [Frantic Factory: Power Shed]", map_id=26, map_dest=29, exit_dest=0, uses_diddy=False, uses_lanky=False, uses_tiny=False, uses_chunky=False, ),
    MapData( "Frantic Factory [Frantic Factory: Crusher Room]", map_id=26, map_dest=36, exit_dest=8, ),
    MapData( "Frantic Factory [Frantic Factory: Car Race]", map_id=26, map_dest=27, exit_dest=0, uses_dk=False, uses_diddy=False, uses_lanky=False, uses_chunky=False, ),
    MapData( "Frantic Factory: Power Shed [Frantic Factory]", map_id=29, map_dest=26, exit_dest=3, ),
    MapData( "Frantic Factory: Crusher Room [Frantic Factory]", map_id=36, map_dest=26, exit_dest=8, ),
    MapData( "Frantic Factory: Car Race [Frantic Factory]", map_id=27, map_dest=26, exit_dest=999, ),

    MapData( "Gloomy Galleon Lobby [DK Isles Overworld]", map_id=174, map_dest=34, exit_dest=5, ),
    MapData( "Gloomy Galleon Lobby [Gloomy Galleon]", map_id=174, map_dest=30, exit_dest=999, ),
    MapData( "Gloomy Galleon [Gloomy Galleon Lobby]", map_id=30, map_dest=174, exit_dest=999, ),
    MapData( "Gloomy Galleon [Gloomy Galleon: 5 Door Ship #3 (DK)]", map_id=30, map_dest=46, exit_dest=0, uses_diddy=False, uses_lanky=False, uses_tiny=False, uses_chunky=False, ),
    MapData( "Gloomy Galleon [Gloomy Galleon: 5 Door Ship #5 (Tiny)]", map_id=30, map_dest=46, exit_dest=1, uses_dk=False, uses_diddy=False, uses_lanky=False, uses_chunky=False, ),
    MapData( "Gloomy Galleon [Gloomy Galleon: 5 Door Ship #2 (Diddy)]", map_id=30, map_dest=43, exit_dest=0, uses_dk=False, uses_lanky=False, uses_tiny=False, uses_chunky=False, ),
    MapData( "Gloomy Galleon [Gloomy Galleon: 5 Door Ship Top (Chunky)]", map_id=30, map_dest=43, exit_dest=1, uses_dk=False, uses_diddy=False, uses_lanky=False, uses_tiny=False, ),
    MapData( "Gloomy Galleon [Gloomy Galleon: 5 Door Ship #4 (Lanky)]", map_id=30, map_dest=43, exit_dest=2, uses_dk=False, uses_diddy=False, uses_tiny=False, uses_chunky=False, ),
    MapData( "Gloomy Galleon [Gloomy Galleon: 2 Door Ship Top (Tiny)]", map_id=30, map_dest=47, exit_dest=0, uses_dk=False, uses_diddy=False, uses_lanky=False, uses_chunky=False, ),
    MapData( "Gloomy Galleon [Gloomy Galleon: 2 Door Ship Bottom (Lanky)]", map_id=30, map_dest=47, exit_dest=1, uses_dk=False, uses_diddy=False, uses_tiny=False, uses_chunky=False, ),
    MapData( "Gloomy Galleon [Gloomy Galleon: Seal Race]", map_id=30, map_dest=39, exit_dest=0, uses_diddy=False, uses_lanky=False, uses_tiny=False, uses_chunky=False, ),
    MapData( "Gloomy Galleon [Gloomy Galleon: Submarine]", map_id=30, map_dest=179, exit_dest=0, uses_dk=False, uses_diddy=False, uses_lanky=False, uses_chunky=False, ),
    MapData( "Gloomy Galleon [Gloomy Galleon: Treasure Chest]", map_id=30, map_dest=44, exit_dest=0, uses_dk=False, uses_diddy=False, uses_lanky=False, uses_chunky=False, ),
    MapData( "Gloomy Galleon [Gloomy Galleon: Mermaid]", map_id=30, map_dest=45, exit_dest=0, uses_dk=False, uses_diddy=False, uses_lanky=False, uses_chunky=False, ),
    MapData( "Gloomy Galleon [Gloomy Galleon: Lighthouse]", map_id=30, map_dest=49, exit_dest=0, uses_diddy=False, uses_lanky=False, uses_tiny=False, uses_chunky=False, ),
    MapData( "Gloomy Galleon [Gloomy Galleon: K. Rool's Ship]", map_id=30, map_dest=31, exit_dest=999, uses_dk=False, uses_diddy=False, uses_lanky=False, uses_tiny=False, ),
    MapData( "Gloomy Galleon [Gloomy Galleon: Mechanical Fish]", map_id=30, map_dest=51, exit_dest=999, uses_dk=False, uses_lanky=False, uses_tiny=False, uses_chunky=False, ),
    MapData( "Gloomy Galleon: 5 Door Ship #3 (DK) [Gloomy Galleon]", map_id=46, map_dest=30, exit_dest=7, ),
    MapData( "Gloomy Galleon: 5 Door Ship #5 (Tiny) [Gloomy Galleon]", map_id=46, map_dest=30, exit_dest=6, ),
    MapData( "Gloomy Galleon: 5 Door Ship #2 (Diddy) [Gloomy Galleon]", map_id=43, map_dest=30, exit_dest=1, ),
    MapData( "Gloomy Galleon: 5 Door Ship Top (Chunky) [Gloomy Galleon]", map_id=43, map_dest=30, exit_dest=2, ),
    MapData( "Gloomy Galleon: 5 Door Ship #4 (Lanky) [Gloomy Galleon]", map_id=43, map_dest=30, exit_dest=3, ),
    MapData( "Gloomy Galleon: 2 Door Ship Top (Tiny) [Gloomy Galleon]", map_id=47, map_dest=30, exit_dest=8, ),
    MapData( "Gloomy Galleon: 2 Door Ship Bottom (Lanky) [Gloomy Galleon]", map_id=47, map_dest=30, exit_dest=9, ),
    MapData( "Gloomy Galleon: Seal Race [Gloomy Galleon]", map_id=39, map_dest=30, exit_dest=999, ),
    MapData( "Gloomy Galleon: Submarine [Gloomy Galleon]", map_id=179, map_dest=30, exit_dest=21, ),
    MapData( "Gloomy Galleon: Treasure Chest [Gloomy Galleon]", map_id=44, map_dest=30, exit_dest=4, ),
    MapData( "Gloomy Galleon: Mermaid [Gloomy Galleon]", map_id=45, map_dest=30, exit_dest=5, ),
    MapData( "Gloomy Galleon: Lighthouse [Gloomy Galleon]", map_id=49, map_dest=30, exit_dest=10, ),
    MapData( "Gloomy Galleon: K. Rool's Ship [Gloomy Galleon]", map_id=31, map_dest=30, exit_dest=11, ),
    MapData( "Gloomy Galleon: Mechanical Fish [Gloomy Galleon]", map_id=51, map_dest=30, exit_dest=999, ),

    MapData( "Fungi Forest Lobby [DK Isles Overworld]", map_id=178, map_dest=34, exit_dest=6, ),
    MapData( "Fungi Forest Lobby [Fungi Forest]", map_id=178, map_dest=48, exit_dest=999, ),
    MapData( "Fungi Forest [Fungi Forest Lobby]", map_id=48, map_dest=178, exit_dest=999, ),
    MapData( "Fungi Forest [Fungi Forest: Minecart]", map_id=48, map_dest=55, exit_dest=999, uses_dk=False, uses_diddy=False, uses_lanky=False, uses_tiny=False, ), # Needs Testing
    MapData( "Fungi Forest [Fungi Forest: Lanky's Attic]", map_id=48, map_dest=58, exit_dest=0, uses_dk=False, uses_diddy=False, uses_tiny=False, uses_chunky=False, ),
    MapData( "Fungi Forest [Fungi Forest: Diddy's Barn]", map_id=48, map_dest=56, exit_dest=0, uses_dk=False, uses_lanky=False, uses_tiny=False, uses_chunky=False, ),
    MapData( "Fungi Forest [Fungi Forest: Diddy's Attic]", map_id=48, map_dest=57, exit_dest=0, uses_dk=False, uses_lanky=False, uses_tiny=False, uses_chunky=False, ),
    MapData( "Fungi Forest [Fungi Forest: DK's Barn]", map_id=48, map_dest=59, exit_dest=0, uses_diddy=False, uses_lanky=False, uses_tiny=False, uses_chunky=False, ),
    MapData( "Fungi Forest [Fungi Forest: Mill (Night Entrance)]", map_id=48, map_dest=62, exit_dest=0, uses_dk=False, uses_diddy=False, uses_lanky=False, uses_tiny=False, ), # Needs Testing
    MapData( "Fungi Forest [Fungi Forest: Mill (Day Entrance)]", map_id=48, map_dest=61, exit_dest=0, ),
    MapData( "Fungi Forest [Fungi Forest: Mill (Tiny Entrance)]", map_id=48, map_dest=62, exit_dest=3, uses_dk=False, uses_diddy=False, uses_lanky=False, uses_chunky=False, ),
    MapData( "Fungi Forest [Fungi Forest: Giant Mushroom (Bottom)]", map_id=48, map_dest=64, exit_dest=0, ),
    MapData( "Fungi Forest [Fungi Forest: Giant Mushroom (Lower Mid)]", map_id=48, map_dest=64, exit_dest=2, ),
    MapData( "Fungi Forest [Fungi Forest: Giant Mushroom (Upper Mid)]", map_id=48, map_dest=64, exit_dest=1, ),
    MapData( "Fungi Forest [Fungi Forest: Giant Mushroom (Vines)]", map_id=48, map_dest=64, exit_dest=3, ),
    MapData( "Fungi Forest [Fungi Forest: Giant Mushroom (Top)]", map_id=48, map_dest=64, exit_dest=4, ),
    MapData( "Fungi Forest [Fungi Forest: Mushroom Puzzle]", map_id=48, map_dest=63, exit_dest=0, uses_dk=False, uses_diddy=False, uses_tiny=False, uses_chunky=False, ),
    MapData( "Fungi Forest [Fungi Forest: Mushrom Spring]", map_id=48, map_dest=70, exit_dest=0, uses_dk=False, uses_diddy=False, uses_tiny=False, uses_chunky=False, ),
    MapData( "Fungi Forest [Fungi Forest: Shooting Game]", map_id=48, map_dest=71, exit_dest=0, uses_dk=False, uses_diddy=False, uses_lanky=False, uses_tiny=False, ),
    MapData( "Fungi Forest [Fungi Forest: Ant Hill]", map_id=48, map_dest=52, exit_dest=0, uses_dk=False, uses_diddy=False, uses_lanky=False, uses_chunky=False, ),
    MapData( "Fungi Forest: Minecart [Fungi Forest]", map_id=55, map_dest=48, exit_dest=16, ),
    MapData( "Fungi Forest: Lanky's Attic [Fungi Forest]", map_id=58, map_dest=48, exit_dest=1, ),
    MapData( "Fungi Forest: Diddy's Barn [Fungi Forest]", map_id=56, map_dest=48, exit_dest=3, ),
    MapData( "Fungi Forest: Diddy's Attic [Fungi Forest]", map_id=57, map_dest=48, exit_dest=2, ),
    MapData( "Fungi Forest: DK's Barn [Fungi Forest]", map_id=59, map_dest=48, exit_dest=4, ),
    MapData( "Fungi Forest: Mill (Night Entrance) [Fungi Forest]", map_id=62, map_dest=48, exit_dest=5, ),
    MapData( "Fungi Forest: Mill (Day Entrance) [Fungi Forest]", map_id=61, map_dest=48, exit_dest=6, ),
    MapData( "Fungi Forest: Mill (Day) [Fungi Forest: Fungi Forest: Mill (Night)]", map_id=61, map_dest=62, exit_dest=2, ),
    MapData( "Fungi Forest: Mill (Night) [Fungi Forest: Fungi Forest: Mill (Day)]", map_id=62, map_dest=61, exit_dest=1, ),
    MapData( "Fungi Forest: Mill (Tiny Entrance) [Fungi Forest]", map_id=62, map_dest=48, exit_dest=7, uses_dk=False, uses_diddy=False, uses_lanky=False, uses_chunky=False, ),
    MapData( "Fungi Forest: Mill (Spider Entrance) [Fungi Forest: Giant Spider]", map_id=62, map_dest=60, exit_dest=0, ),
    MapData( "Fungi Forest: Giant Spider [Fungi Forest: Mill (Spider Entrance)]", map_id=60, map_dest=62, exit_dest=1, ),
    MapData( "Fungi Forest: Giant Mushroom (Bottom) [Fungi Forest]", map_id=64, map_dest=48, exit_dest=8, ),
    MapData( "Fungi Forest: Giant Mushroom (Lower Mid) [Fungi Forest]", map_id=64, map_dest=48, exit_dest=9, ),
    MapData( "Fungi Forest: Giant Mushroom (Upper Mid) [Fungi Forest]", map_id=64, map_dest=48, exit_dest=10, ),
    MapData( "Fungi Forest: Giant Mushroom (Vines) [Fungi Forest]", map_id=64, map_dest=48, exit_dest=11, ),
    MapData( "Fungi Forest: Giant Mushroom (Top) [Fungi Forest]", map_id=64, map_dest=48, exit_dest=12, ),
    MapData( "Fungi Forest: Mushroom Puzzle [Fungi Forest]", map_id=63, map_dest=48, exit_dest=14, ),
    MapData( "Fungi Forest: Mushrom Spring [Fungi Forest]", map_id=70, map_dest=48, exit_dest=15, ),
    MapData( "Fungi Forest: Shooting Game [Fungi Forest]", map_id=71, map_dest=48, exit_dest=13, ),
    MapData( "Fungi Forest: Ant Hill [Fungi Forest]", map_id=52, map_dest=48, exit_dest=23, ),

    MapData( "Crystal Caves Lobby [DK Isles Overworld]", map_id=194, map_dest=34, exit_dest=10, ),
    MapData( "Crystal Caves Lobby [Crystal Caves]", map_id=194, map_dest=72, exit_dest=999, ),
    MapData( "Crystal Caves [Crystal Caves Lobby]", map_id=72, map_dest=194, exit_dest=999, ),
    MapData( "Crystal Caves [Crystal Caves: Igloo (Diddy)]", map_id=72, map_dest=100, exit_dest=0, uses_dk=False, uses_lanky=False, uses_tiny=False, uses_chunky=False, ),
    MapData( "Crystal Caves [Crystal Caves: Igloo (DK)]", map_id=72, map_dest=86, exit_dest=0, uses_diddy=False, uses_lanky=False, uses_tiny=False, uses_chunky=False, ),
    MapData( "Crystal Caves [Crystal Caves: Igloo (Lanky)]", map_id=72, map_dest=85, exit_dest=0, uses_dk=False, uses_diddy=False, uses_tiny=False, uses_chunky=False, ),
    MapData( "Crystal Caves [Crystal Caves: Igloo (Chunky)]", map_id=72, map_dest=95, exit_dest=0, uses_dk=False, uses_diddy=False, uses_lanky=False, uses_tiny=False, ),
    MapData( "Crystal Caves [Crystal Caves: Igloo (Tiny)]", map_id=72, map_dest=84, exit_dest=0, uses_dk=False, uses_diddy=False, uses_lanky=False, uses_chunky=False, ),
    MapData( "Crystal Caves [Crystal Caves: Ice Castle]", map_id=72, map_dest=98, exit_dest=0, uses_dk=False, uses_diddy=False, uses_tiny=False, uses_chunky=False, ),
    MapData( "Crystal Caves [Crystal Caves: Beetle Race]", map_id=72, map_dest=82, exit_dest=0, uses_dk=False, uses_diddy=False, uses_tiny=False, uses_chunky=False, ),
    MapData( "Crystal Caves [Crystal Caves: 5 Door Cabin (DK)]", map_id=72, map_dest=91, exit_dest=0, uses_diddy=False, uses_lanky=False, uses_tiny=False, uses_chunky=False, ),
    MapData( "Crystal Caves [Crystal Caves: 5 Door Cabin (Chunky)]", map_id=72, map_dest=90, exit_dest=0, uses_dk=False, uses_diddy=False, uses_lanky=False, uses_tiny=False, ),
    MapData( "Crystal Caves [Crystal Caves: 5 Door Cabin (Tiny)]", map_id=72, map_dest=93, exit_dest=0, uses_dk=False, uses_diddy=False, uses_lanky=False, uses_chunky=False, ),
    MapData( "Crystal Caves [Crystal Caves: 5 Door Cabin (Diddy Middle)]", map_id=72, map_dest=92, exit_dest=0, uses_dk=False, uses_lanky=False, uses_tiny=False, uses_chunky=False, ),
    MapData( "Crystal Caves [Crystal Caves: 5 Door Cabin (Diddy Top)]", map_id=72, map_dest=200, exit_dest=0, uses_dk=False, uses_lanky=False, uses_tiny=False, uses_chunky=False, ),
    MapData( "Crystal Caves [Crystal Caves: 1 Door Cabin (DK)]", map_id=72, map_dest=89, exit_dest=0, uses_diddy=False, uses_lanky=False, uses_tiny=False, uses_chunky=False, ),
    MapData( "Crystal Caves [Crystal Caves: 1 Door Cabin (Lanky)]", map_id=72, map_dest=94, exit_dest=0, uses_dk=False, uses_diddy=False, uses_tiny=False, uses_chunky=False, ),
    MapData( "Crystal Caves: Igloo (Diddy) [Crystal Caves]", map_id=100, map_dest=72, exit_dest=1, ),
    MapData( "Crystal Caves: Igloo (DK) [Crystal Caves]", map_id=86, map_dest=72, exit_dest=2, ),
    MapData( "Crystal Caves: Igloo (Lanky) [Crystal Caves]", map_id=85, map_dest=72, exit_dest=3, ),
    MapData( "Crystal Caves: Igloo (Chunky) [Crystal Caves]", map_id=95, map_dest=72, exit_dest=4, ),
    MapData( "Crystal Caves: Igloo (Tiny) [Crystal Caves]", map_id=84, map_dest=72, exit_dest=5, ),
    MapData( "Crystal Caves: Ice Castle [Crystal Caves]", map_id=98, map_dest=72, exit_dest=30, ),
    MapData( "Crystal Caves: Beetle Race [Crystal Caves]", map_id=82, map_dest=72, exit_dest=999, ),
    MapData( "Crystal Caves: 5 Door Cabin (DK) [Crystal Caves]", map_id=91, map_dest=72, exit_dest=14, ),
    MapData( "Crystal Caves: 5 Door Cabin (Chunky) [Crystal Caves]", map_id=90, map_dest=72, exit_dest=15, ),
    MapData( "Crystal Caves: 5 Door Cabin (Tiny) [Crystal Caves]", map_id=93, map_dest=72, exit_dest=16, ),
    MapData( "Crystal Caves: 5 Door Cabin (Diddy Middle) [Crystal Caves]", map_id=92, map_dest=72, exit_dest=17, ),
    MapData( "Crystal Caves: 5 Door Cabin (Diddy Top) [Crystal Caves]", map_id=200, map_dest=72, exit_dest=18, ),
    MapData( "Crystal Caves: 1 Door Cabin (DK) [Crystal Caves]", map_id=89, map_dest=72, exit_dest=19, ),
    MapData( "Crystal Caves: 1 Door Cabin (Lanky) [Crystal Caves]", map_id=94, map_dest=72, exit_dest=20, ),

    MapData( "Creepy Castle Lobby [DK Isles Overworld]", map_id=193, map_dest=34, exit_dest=11, ),
    MapData( "Creepy Castle Lobby [Creepy Castle]", map_id=193, map_dest=87, exit_dest=999, ),
    MapData( "Creepy Castle [Creepy Castle Lobby]", map_id=87, map_dest=193, exit_dest=999, ),
    MapData( "Creepy Castle [Creepy Castle: Tree]", map_id=87, map_dest=164, exit_dest=0, uses_diddy=False, uses_lanky=False, uses_tiny=False, uses_chunky=False, ),
    MapData( "Creepy Castle [Creepy Castle: Crypt]", map_id=87, map_dest=183, exit_dest=0, ),
    MapData( "Creepy Castle [Creepy Castle: Basement (Moat Side)]", map_id=87, map_dest=151, exit_dest=0, ),
    MapData( "Creepy Castle [Creepy Castle: Basement (Crypt Side)]", map_id=87, map_dest=151, exit_dest=2, ),
    MapData( "Creepy Castle [Creepy Castle: Museum]", map_id=87, map_dest=113, exit_dest=0, uses_dk=False, uses_diddy=False, uses_lanky=False, uses_tiny=False, ),
    MapData( "Creepy Castle [Creepy Castle: Ballroom]", map_id=87, map_dest=88, exit_dest=0, ),
    MapData( "Creepy Castle [Creepy Castle: Library (Cloud)]", map_id=87, map_dest=114, exit_dest=0, uses_diddy=False, uses_lanky=False, uses_tiny=False, uses_chunky=False, ),
    MapData( "Creepy Castle [Creepy Castle: Library (Walkway)]", map_id=87, map_dest=114, exit_dest=1, ), # Revisit, maybe not possible
    MapData( "Creepy Castle [Creepy Castle: Tower]", map_id=87, map_dest=105, exit_dest=0, uses_dk=False, uses_diddy=False, uses_tiny=False, uses_chunky=False, ),
    MapData( "Creepy Castle [Creepy Castle: Trash Can]", map_id=87, map_dest=167, exit_dest=0, uses_dk=False, uses_diddy=False, uses_lanky=False, uses_chunky=False, ),
    MapData( "Creepy Castle [Creepy Castle: Greenhouse]", map_id=87, map_dest=168, exit_dest=0, uses_dk=False, uses_diddy=False, uses_tiny=False, uses_chunky=False, ),
    MapData( "Creepy Castle [Creepy Castle: Shed]", map_id=87, map_dest=166, exit_dest=0, uses_dk=False, uses_diddy=False, uses_lanky=False, uses_tiny=False, ),
    MapData( "Creepy Castle: Tree [Creepy Castle]", map_id=164, map_dest=87, exit_dest=15, ),
    MapData( "Creepy Castle: Tree (Water) [Creepy Castle]", map_id=164, map_dest=87, exit_dest=1, ),
    MapData( "Creepy Castle: Crypt [Creepy Castle]", map_id=183, map_dest=87, exit_dest=4, ),
    MapData( "Creepy Castle: Crypt [Creepy Castle: Inner Crypt (Lanky, Tiny)]", map_id=183, map_dest=108, exit_dest=0, uses_dk=False, uses_diddy=False, uses_chunky=False, ),
    MapData( "Creepy Castle: Crypt [Creepy Castle: Inner Crypt (DK, Diddy, Chunky)]", map_id=183, map_dest=112, exit_dest=0, uses_lanky=False, uses_tiny=False, ),
    MapData( "Creepy Castle: Inner Crypt (Lanky, Tiny) [Creepy Castle: Crypt]", map_id=108, map_dest=183, exit_dest=4, ),
    MapData( "Creepy Castle: Inner Crypt (DK, Diddy, Chunky) [Creepy Castle: Crypt]", map_id=112, map_dest=183, exit_dest=3, ),
    MapData( "Creepy Castle: Inner Crypt (DK, Diddy, Chunky) [Creepy Castle: Minecart]", map_id=112, map_dest=106, exit_dest=0, uses_diddy=False, uses_lanky=False, uses_tiny=False, uses_chunky=False, ),
    MapData( "Creepy Castle: Minecart [Creepy Castle: Inner Crypt (DK, Diddy, Chunky)]", map_id=106, map_dest=112, exit_dest=1, ),
    MapData( "Creepy Castle: Basement (Moat Side) [Creepy Castle]", map_id=151, map_dest=87, exit_dest=2, ),
    MapData( "Creepy Castle: Basement (Crypt Side) [Creepy Castle]", map_id=151, map_dest=87, exit_dest=5, ),
    MapData( "Creepy Castle: Basement (Middle) [Creepy Castle: Dungeon]", map_id=151, map_dest=163, exit_dest=0, ),
    MapData( "Creepy Castle: Dungeon [Creepy Castle: Basement (Middle)]", map_id=163, map_dest=151, exit_dest=4, ),
    MapData( "Creepy Castle: Museum [Creepy Castle]", map_id=113, map_dest=87, exit_dest=7, ),
    MapData( "Creepy Castle: Museum [Creepy Castle: Car Race]", map_id=113, map_dest=185, exit_dest=0, uses_dk=False, uses_diddy=False, uses_lanky=False, uses_chunky=False, ),
    MapData( "Creepy Castle: Car Race [Creepy Castle: Museum]", map_id=185, map_dest=113, exit_dest=999, ),
    MapData( "Creepy Castle: Ballroom [Creepy Castle]", map_id=88, map_dest=87, exit_dest=11, ),
    MapData( "Creepy Castle: Library (Cloud) [Creepy Castle]", map_id=114, map_dest=87, exit_dest=12, ),
    MapData( "Creepy Castle: Library (Walkway) [Creepy Castle]", map_id=114, map_dest=87, exit_dest=13, uses_diddy=False, uses_lanky=False, uses_tiny=False, uses_chunky=False, ),
    MapData( "Creepy Castle: Tower [Creepy Castle]", map_id=105, map_dest=87, exit_dest=14, ),
    MapData( "Creepy Castle: Trash Can [Creepy Castle]", map_id=167, map_dest=87, exit_dest=16, ),
    MapData( "Creepy Castle: Greenhouse [Creepy Castle]", map_id=168, map_dest=87, exit_dest=8, ),
    MapData( "Creepy Castle: Greenhouse (Back) [Creepy Castle]", map_id=168, map_dest=87, exit_dest=20, ),
    MapData( "Creepy Castle: Shed [Creepy Castle]", map_id=166, map_dest=87, exit_dest=9, ),

    # K. Lumsy and Hideout Helm should always be in the expected location
    # MapData( "DK Isles Overworld (K. Lumsy)", map_id=34, map_dest=97, exit_dest=0, ),
    # MapData( "K. Lumsy (DK Isles Overworld)", map_id=97, map_dest=34, exit_dest=1, ),
    # MapData( "Hideout Helm Lobby [DK Isles Overworld]", map_id=170, map_dest=34, exit_dest=7, ),
    # MapData( "Hideout Helm Lobby [Hideout Helm]", map_id=170, map_dest=17, exit_dest=0, ),
    # MapData( "Hideout Helm [Hideout Helm Lobby]", map_id=17, map_dest=170, exit_dest=0, ),

    # Removed so its easier to free Lanky and Tiny
    # MapData( "Angry Aztec [Angry Aztec: Tiny's Temple]", map_id=38, map_dest=16, exit_dest=0, ),
    # MapData( "Angry Aztec [Angry Aztec: Llama Temple]", map_id=38, map_dest=20, exit_dest=0, ),
]

map_list = [
    MapData( "DK Isles Overworld", map_id=34, ),
    MapData( "DK Isles: Training Grounds", map_id=176, ),
    MapData( "DK Isles: DK's House", map_id=171, ),
    MapData( "DK Isles: Fairy Island", map_id=189, ),
    MapData( "DK Isles: Snide's Room", map_id=195, ),

    MapData( "Jungle Japes Lobby", map_id=169, ),
    MapData( "Jungle Japes Main", map_id=7, ),
    MapData( "Jungle Japes: Mountain", map_id=4, ),
    MapData( "Jungle Japes: Minecart", map_id=6, ),
    MapData( "Jungle Japes: Lanky's Cave", map_id=13, ),
    MapData( "Jungle Japes: Shell", map_id=12, ),
    MapData( "Jungle Japes: Chunky's Cave", map_id=33, ),

    MapData( "Angry Aztec Lobby", map_id=173, ),
    MapData( "Angry Aztec Main", map_id=38, ),
    MapData( "Angry Aztec: Tiny's Temple", map_id=16, ),
    MapData( "Angry Aztec: Llama Temple", map_id=20, ),
    MapData( "Angry Aztec: 5 Door Temple (DK)", map_id=19, ),
    MapData( "Angry Aztec: 5 Door Temple (Diddy)", map_id=21, ),
    MapData( "Angry Aztec: 5 Door Temple (Lanky)", map_id=23, ),
    MapData( "Angry Aztec: 5 Door Temple (Tiny)", map_id=22, ),
    MapData( "Angry Aztec: 5 Door Temple (Chunky)", map_id=24, ),
    MapData( "Angry Aztec: Beetle Race", map_id=14, ),

    MapData( "Frantic Factory Lobby", map_id=175, ),
    MapData( "Frantic Factory Main", map_id=26, ),
    MapData( "Frantic Factory: Power Shed", map_id=29, ),
    MapData( "Frantic Factory: Crusher Room", map_id=36, ),
    MapData( "Frantic Factory: Car Race", map_id=27, ),

    MapData( "Gloomy Galleon Lobby", map_id=174, ),
    MapData( "Gloomy Galleon Main", map_id=30, ),
    MapData( "Gloomy Galleon: 5 Door Ship (DK, Tiny)", map_id=46, ),
    MapData( "Gloomy Galleon: 5 Door Ship (Diddy, Lanky, Chunky)", map_id=43, ),
    MapData( "Gloomy Galleon: 2 Door Ship", map_id=47, ),
    MapData( "Gloomy Galleon: Seal Race", map_id=39, ),
    MapData( "Gloomy Galleon: Submarine", map_id=179, ),
    MapData( "Gloomy Galleon: Treasure Chest", map_id=44, ),
    MapData( "Gloomy Galleon: Mermaid", map_id=45, ),
    MapData( "Gloomy Galleon: Lighthouse", map_id=49, ),
    MapData( "Gloomy Galleon: K. Rool's Ship", map_id=31, ),
    MapData( "Gloomy Galleon: Mechanical Fish", map_id=51, ),

    MapData( "Fungi Forest Lobby", map_id=178, ),
    MapData( "Fungi Forest Main", map_id=48, ),
    MapData( "Fungi Forest: Minecart", map_id=55, ),
    MapData( "Fungi Forest: Lanky's Attic", map_id=58, ),
    MapData( "Fungi Forest: Diddy's Barn", map_id=56, ),
    MapData( "Fungi Forest: Diddy's Attic", map_id=57, ),
    MapData( "Fungi Forest: DK's Barn", map_id=59, ),
    MapData( "Fungi Forest: Mill (Night Side)", map_id=62, ),
    MapData( "Fungi Forest: Mill (Day Side)", map_id=61, ),
    MapData( "Fungi Forest: Giant Spider", map_id=60, ),
    MapData( "Fungi Forest: Giant Mushroom", map_id=64, ),
    MapData( "Fungi Forest: Mushroom Puzzle", map_id=63, ),
    MapData( "Fungi Forest: Mushrom Spring", map_id=70, ),
    MapData( "Fungi Forest: Shooting Game", map_id=71, ),
    MapData( "Fungi Forest: Ant Hill", map_id=52, ),

    MapData( "Crystal Caves Lobby", map_id=194, ),
    MapData( "Crystal Caves Main", map_id=72, ),
    MapData( "Crystal Caves: Igloo (Diddy)", map_id=100, ),
    MapData( "Crystal Caves: Igloo (DK)", map_id=86, ),
    MapData( "Crystal Caves: Igloo (Lanky)", map_id=85, ),
    MapData( "Crystal Caves: Igloo (Chunky)", map_id=95, ),
    MapData( "Crystal Caves: Igloo (Tiny)", map_id=84, ),
    MapData( "Crystal Caves: Ice Castle", map_id=98, ),
    MapData( "Crystal Caves: Beetle Race", map_id=82, ),
    MapData( "Crystal Caves: 5 Door Cabin (DK)", map_id=91, ),
    MapData( "Crystal Caves: 5 Door Cabin (Chunky)", map_id=90, ),
    MapData( "Crystal Caves: 5 Door Cabin (Tiny)", map_id=93, ),
    MapData( "Crystal Caves: 5 Door Cabin (Diddy Middle)", map_id=92, ),
    MapData( "Crystal Caves: 5 Door Cabin (Diddy Top)", map_id=200, ),
    MapData( "Crystal Caves: 1 Door Cabin (DK)", map_id=89, ),
    MapData( "Crystal Caves: 1 Door Cabin (Lanky)", map_id=94, ),

    MapData( "Creepy Castle Lobby", map_id=193, ),
    MapData( "Creepy Castle Main", map_id=87, ),
    MapData( "Creepy Castle: Tree", map_id=164, ),
    MapData( "Creepy Castle: Crypt", map_id=183, ),
    MapData( "Creepy Castle: Inner Crypt (Lanky, Tiny)", map_id=108, ),
    MapData( "Creepy Castle: Inner Crypt (DK, Diddy, Chunky)", map_id=112, ),
    MapData( "Creepy Castle: Minecart", map_id=106, ),
    MapData( "Creepy Castle: Basement", map_id=151, ),
    MapData( "Creepy Castle: Dungeon", map_id=163, ),
    MapData( "Creepy Castle: Museum", map_id=113, ),
    MapData( "Creepy Castle: Car Race", map_id=185, ),
    MapData( "Creepy Castle: Ballroom", map_id=88, ),
    MapData( "Creepy Castle: Library", map_id=114, ),
    MapData( "Creepy Castle: Tower", map_id=105, ),
    MapData( "Creepy Castle: Trash Can", map_id=167, ),
    MapData( "Creepy Castle: Greenhouse", map_id=168, ),
    MapData( "Creepy Castle: Shed", map_id=166, ),
]